package com.alexdupre.bitpay.models

object LedgerCode extends Enumeration {

  val Invoice                              = Value(1000)
  val Fee                                  = Value(1001)
  val Payment                              = Value(1002)
  val Other                                = Value(1003)
  val FeeRefund                            = Value(1004)
  val Deposit                              = Value(1005)
  val Exchange                             = Value(1006)
  val ExchangeFee                          = Value(1007)
  val PlanCharge                           = Value(1008)
  val PlanProratedCredit                   = Value(1009)
  val PlanUnderutilizationCredit           = Value(1010)
  val PayoffNegativeBalance                = Value(1011)
  val Donation                             = Value(1012)
  val Corrective                           = Value(1013)
  val SettlementFee                        = Value(1014)
  val Custom                               = Value(1016)
  val AccountSettlement                    = Value(1017)
  val OverpaymentCreditFee                 = Value(1018)
  val OverpaymentCredit                    = Value(1019)
  val InvoiceRefund                        = Value(1020)
  val OverpaymentCreditRefund              = Value(1021)
  val CorrectiveForFailedAccountSettlement = Value(1022)
  val InvoiceFee                           = Value(1023)
  val BitcoinDeposit                       = Value(1024)
  val FiatDeposit                          = Value(1025)
  val DonationFee                          = Value(1026)
  val CustomFee                            = Value(1027)
  val AffiliateCommission                  = Value(1030)
  val ManualAffiliateCommission            = Value(1031)
  val MerchantCardDeposit                  = Value(1032)
  val CustomPlanCharge                     = Value(1033)
  val FundingPayoutRequest                 = Value(1034)
  val ManuallyFundingPayoutRequest         = Value(1035)
  val CustomFeeReimbursement               = Value(1036)
  val CustomPlanChargeReimbursement        = Value(1037)
  val TestnetBitcoinSettlement             = Value(1038)
  val RefundFee                            = Value(1039)
  val PayoutFee                            = Value(1040)
  val WireFee                              = Value(1041)
}
